import type { GridApi } from "../types/grid-api.js";
import type { GridOptions } from "../types/grid-options.js";
import type { GridEventMap } from "../types/events.js";

export const gridOptionParityKeys = [
  "columns",
  "columnOrder",
  "columnState",
  "columnUi",
  "headerMerge",
  "data",
  "dataSource",
  "rowModel",
  "infinite",
  "server",
  "viewport",
  "rowKey",
  "width",
  "height",
  "bodyHeight",
  "layout",
  "virtualization",
  "rowHeight",
  "headerHeight",
  "frozenRows",
  "frozenColumns",
  "selection",
  "editing",
  "filtering",
  "sorting",
  "grouping",
  "aggregation",
  "pivot",
  "summary",
  "tree",
  "merge",
  "pagination",
  "clipboard",
  "export",
  "import",
  "contextMenu",
  "accessibility",
  "security",
  "theme",
  "locale",
  "plugins",
  "events"
] as const satisfies readonly (keyof GridOptions<unknown> & string)[];

export const gridEventParityNames = [
  "ready",
  "destroyed",
  "dataRequested",
  "dataLoaded",
  "rowClicked",
  "cellClicked",
  "selectionChanged",
  "sortChanged",
  "filterChanged",
  "pageChanged",
  "cellEditStarted",
  "cellEditStaged",
  "cellEditCommitted",
  "cellEditCancelled",
  "validationFailed",
  "error"
] as const satisfies readonly (keyof GridEventMap<unknown> & string)[];

export const gridApiMethodParityNames = [
  "destroy",
  "refresh",
  "setData",
  "appendRows",
  "updateRows",
  "removeRows",
  "getRow",
  "getSelectionState",
  "getSelectedRows",
  "selectRows",
  "selectCell",
  "selectCellRange",
  "selectAllVisibleRows",
  "selectServerDataset",
  "clearSelection",
  "startEdit",
  "stopEdit",
  "getPendingEdits",
  "commitPendingEdits",
  "cancelPendingEdits",
  "validate",
  "setColumns",
  "showColumn",
  "hideColumn",
  "pinColumn",
  "autoSizeColumn",
  "setFilterModel",
  "getFilterModel",
  "setSortModel",
  "getSortModel",
  "setGroupModel",
  "getGroupModel",
  "expandGroup",
  "collapseGroup",
  "toggleGroup",
  "expandTreeNode",
  "collapseTreeNode",
  "toggleTreeNode",
  "selectTreeNode",
  "getTreeSelection",
  "setPage",
  "getPage",
  "setPageSize",
  "getPageSize",
  "scrollToRow",
  "scrollToColumn",
  "exportData",
  "importData",
  "copyToClipboard",
  "pasteFromClipboard",
  "applyTheme",
  "setLocale",
  "getLocale",
  "on",
  "off"
] as const satisfies readonly (keyof GridApi<unknown> & string)[];

export type GridOptionParityKey = typeof gridOptionParityKeys[number];
export type GridEventParityName = typeof gridEventParityNames[number];
export type GridApiMethodParityName = typeof gridApiMethodParityNames[number];
